version: "3.7"
networks:
  window-code-space:
    name: window-code-space
services:
  nginx:
    image: nginx
    volumes:
      - "./html:/usr/share/nginx/html"
      - "./php:/usr/share/nginx/php"
    # command: 
    #   - -c /my-nginx/nginx.conf
    # entrypoint: nginx
    ports:
      - "80:80"
    networks:
      - window-code-space
